import './models/user';
import './models/appointment';
import './models/consultation';
import './models/doctor';
import './models/facility';
import './models/schedule';
import './models/hospital';
import './models/hospitalAdmin';
import './models/specialization';
